name = "bankai"
compatibility_date = "2026-06-04"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "bankai-comments"
database_id = "b4af6a4c-3848-443c-8087-1baa799b0a65"
